http://localhost:3000/rawPost

###

GET http://localhost:3000/rawPost HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/rawPost HTTP/1.1
content-type: application/json

###

PATCH http://localhost:3000/rawPost/1 HTTP/1.1
content-type: application/json

{
  "comments": [
      {
         "id": 7,
        "respondsTo": null,
        "author": {
          "id": 7,
          "username": "Teste 2"
        },
        "timestamp": "2019-02-28T08:21Z",
        "content": "Testando 222222"
      }
    ]
}

###

PUT http://localhost:8000/rawPost/1 HTTP/1.1
content-type: application/json

{
  "nome": "Angular 17"
}

###

DELETE http://localhost:8000/rawPost/----
